# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: switchfully-intakeapp-frontend
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: switchfully-intakeapp-frontend
    verbose: true
    customCommand: 'run build'